### ISSUE TITLE
hide progress bar

### ISSUE THREAD

**Issue by gustavomc** [JakeSteam/Vidsta#1]
is there a way to hide progress bar?

**Comment by JakeSteam** [comment]
Hey @gustavomc ,

Not currently, but it can certainly be in the next release. Are you looking for it to disappear when playing, like the play / pause buttons do?

Jake

**Comment by gustavomc** [comment]
thanks for your answer @JakeSteam, im looking for completely remove the progressbar. another question, does it play youtube videos?

**Comment by JakeSteam** [comment]
Hey,

No problem, will add the option into the next release (or you're of course welcome to make a pull request).

Not natively, it only plays local / remote files it has a URL for. If you can use some other technique to get the video file URL, it might work?
